terraform workflow updated

diff --git a/.github/workflows/terraform-infra.yml b/.github/workflows/terraform-infra.yml
--- a/.github/workflows/terraform-infra.yml
+++ b/.github/workflows/terraform-infra.yml
@@ -45,9 +45,9 @@ jobs:
         run: terraform plan -no-color -input=false -out planfile
         continue-on-error: true
 
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform plan status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
       
       - name: Terraform apply
         id: apply
